name: Pull Request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 9.15.0
      - name: Setup Node.js 22
        uses: actions/setup-node@v4.2.0
        with:
          node-version: "22.12.0"
          cache: "pnpm"
      - name: install project dependencies
        run: pnpm install --frozen-lockfile
      - name: lint project
        run: pnpm lint
      - name: build project
        run: pnpm build
